### ISSUE TITLE
Dataset request

### ISSUE THREAD

**Issue by caneatonly** [nathan-g1/mm-transformer-model#2]
Hello. Could you provide the image and mask datasets used in the "u-net-auto.ipynb"

**Comment by nathan-g1** [comment]
Hello @caneatonly, [this](https://www.youtube.com/watch?v=LQltwzm78_o) video link will help you download the files first and then you can use `Autolabeling_IS2_using_S2_iqr_2023.ipynb` to help you create your own images/mask datasets.
